name: Android CI

on:
  push:
    branches: [ "base" ]
  pull_request:
    branches: [ "base" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        git submodule sync
        git submodule update --init --recursive
        
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        submodules: true
        token: ${{ secrets.STOKEN }}

      

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
